package com.findmeahometeam.reskiume.domain.repository.remote.database.remoteUser

import kotlinx.coroutines.flow.StateFlow

interface RealtimeDatabaseRemoteUserRepositoryForIosDelegateWrapper {
    val realtimeDatabaseRemoteUserRepositoryForIosDelegateState: StateFlow<RealtimeDatabaseRemoteUserRepositoryForIosDelegate?>
    fun updateRealtimeDatabaseRemoteUserRepositoryForIosDelegate(delegate: RealtimeDatabaseRemoteUserRepositoryForIosDelegate?)
}
